scan_filter_chain:
# - name: angle
#   type: laser_filters/LaserScanAngularBoundsFilter
#   params:
#     lower_angle: -2.2  
#     upper_angle: 2.2

- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    lower_threshold: 0.2
    upper_threshold: 5.0
    lower_replacement_value: -.inf
    upper_replacement_value: .inf

# - name: box_filter
#   type: laser_filters/LaserScanBoxFilter
#   params:
#     box_frame: laser
#     max_x: 8.0
#     max_y: 2.0
#     max_z: 0.1
#     min_x: -0.0
#     min_y: -2.0
#     min_z: -0.1
#     invert: true
# - name: speckle_filter
#   type: laser_filters/LaserScanSpeckleFilter
#   params:
#     filter_type: 1
#     max_range: 3.0
#     max_range_difference: 0.2
#     filter_window: 3